service: portfolio
package:
  exclude:
    - gatsby-portfolio/**
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-west-1
  memorySize: 128
  httpApi:
    cors: true
    payload: "2.0"
functions:
  app: # A Function. Name it whatever you like.
    handler: index.handler # The file and module for this specific function.
    events:
      - httpApi: # HTTP API endpoint
          path: /
          method: "*"
      - httpApi:
          path: /{proxy+}
          method: "*"
