version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: cd gatsby-portfolio && yarn install
            - run: npm run clean
            - run: npm run build
            - run: npm run deploy
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
